### ISSUE TITLE
Zip compression needed

### ISSUE THREAD

**Issue by randomascii** [google/UIforETW#1]
Currently the only supported form of trace compression in UIforETW is what is built in to Windows 8 and above. If you are recording or viewing traces on Windows 7 you are out of luck. Transparent .zip file compression would be very helpful. The idea would be to compress each trace into a .zip file with the same name and then delete the .etl file. The .zip file will still show up in the trace list (that code is there already), and UIforETW would need to automatically extract the trace on demand.

Traces could be automatically deleted when they haven't been referenced in a while (garbage collection) or they could be deleted whenever the compress-all-traces command is executed.

**Comment by randomascii** [comment]
Note that WPA can read .etl files that are in .zip files, so it would be easy enough to add an option to zip up traces. The benefits are pretty mild however.

It would be even easier to just add support for passing .zip files along to WPA, so that users could just compress them themselves. Less work, but still barely worth it.

**Comment by jeffstokes72** [comment]
The 7zip libraries appear to be commercially available under OSS.

[7zip link](http://www.7-zip.org/faq.html#developer_faq)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/google/UIforETW/issues/1#issue-67970987

@randomascii, does this still apply? I doubt that performance evaluation for Windows 7 remains a common endeavour.

**Comment by randomascii** [comment]
It seems this is no longer applicable. UIforETW doesn't support Windows 7 anymore. I will close this.
