### ISSUE TITLE
etw 149 on windows 7

### ISSUE THREAD

**Issue by nickcasa** [google/UIforETW#111]
i need to run this on win7, however the latest package references xperf.exe as being located in a win 10 location, how can i get around this?  i already have the win7 sdk with xperf on the windows 7 vm.  thanks.  
![11](https://user-images.githubusercontent.com/33458297/32500320-0c6e5bac-c3a3-11e7-820e-74bb78fdcf97.jpg)

**Comment by randomascii** [comment]
That location is for the Windows 10 SDK. Early versions of the Win 10 SDK will install fine on Windows 7.

Unfortunately, more recent versions of the Windows 10 SDK will not. I searched the commit history to find exactly what the status is and found this:

commit 28725f10cd48e53aca9bb43a7d0144b35e8c375b
Author: Bruce Dawson <bruce.dawson@cygnus-software.com>
Date:   Tue Aug 23 09:03:14 2016 -0700

    Support Windows 7

    Windows 7 can't run the Windows 10 Anniversary edition of WPT. So,
    UIforETW needs to package to WPT installers and select them. It also
    now warns if an unsupported version is installed. It also now checks to
    see whether process creation failed, in order to make the Windows 7
    failures (or future failures) more obvious.

So, if you install the Windows 10 RTM version of WPT then you will be fine - and you will get the new WPT features found there. You could also hack UIforETW to use an earlier version of xperf.exe, but you are on your own then. You can find old SDK versions here:

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

I think you want 10.0.10586.212. Don't install later versions of WPT. They will install but they will not run.

You can also xcopy WPT from another machine that has a working install.

**Comment by randomascii** [comment]
There is nothing to be done here. UIforETW works fine on Windows 7, and the confusion of the Windows Kits\10 directory structure is Microsoft's issue, not UIforETW's.
