### ISSUE TITLE
Trace to file does not work.

### ISSUE THREAD

**Issue by omnimose** [google/UIforETW#113]
Trace to file does not work.

My windows version is "Microsoft Windows [Version 10.0.16299.192]"

Select Trace to File, client Start Tracing, wait for a while, then click Stop Tracing, it shows below, but there is no trace file gets generated:

wevtutil.exe um "D:\docs\tools\etwpackage\bin\etwproviders.man"
wevtutil.exe im "D:\docs\tools\etwpackage\bin\etwproviders.man" /mf:"C:\Users\georgel\AppData\Local\Temp\ETWProviders.dll" /rf:"C:\Users\georgel\AppData\Local\Temp\ETWProviders.dll"

Starting tracing to disk...
xperf.exe -start "NT Kernel Logger" -on Latency+POWER+DISPATCHER+DISK_IO_INIT+FILE_IO+FILE_IO_INIT+VIRT_ALLOC+MEMINFO -stackwalk Profile+CSwitch+ReadyThread -buffersize 1024 -minbuffers 900 -maxbuffers 900 -f "C:\Users\georgel\AppData\Local\Temp\UIForETWkernel.etl" -start UIforETWSession -on Microsoft-Windows-Win32k:0xfdffffffefffffff+Multi-MAIN+Multi-FrameRate+Multi-Input+Multi-Worker+Microsoft-Windows-Kernel-Memory:0xE0+Microsoft-Windows-Kernel-Power -buffersize 1024 -minbuffers 150 -maxbuffers 150 -f "C:\Users\georgel\AppData\Local\Temp\UIForETWuser.etl"
Tracing is started.
xperf.exe -capturestate UIforETWSession Microsoft-Windows-Win32k:0xfdffffffefffffff+Multi-MAIN+Multi-FrameRate+Multi-Input+Multi-Worker+Microsoft-Windows-Kernel-Memory:0xE0+Microsoft-Windows-Kernel-Power

Stopping tracing...
xperf.exe -stop UIforETWSession -stop "NT Kernel Logger"
The trace you have just captured "C:\Users\georgel\AppData\Local\Temp\UIForETWkernel.etl" may contain personally identifiable information, including but not necessarily limited to paths to files accessed, paths to registry accessed and process names. Exact information depends on the events that were logged. Please be aware of this when sharing out this trace with other people.
The trace you have just captured "C:\Users\georgel\AppData\Local\Temp\UIForETWuser.etl" may contain personally identifiable information, including but not necessarily limited to paths to files accessed, paths to registry accessed and process names. Exact information depends on the events that were logged. Please be aware of this when sharing out this trace with other people.
Tracing stopped.

**Comment by randomascii** [comment]
That behavior is by design. "Stop Tracing" is intended to mean "stop tracing without recording any data". "Save Trace Buffers" is what saves the trace. Sorry for the confusion. I'm open to ideas for how to improve the UI to avoid confusion.

**Comment by amaiorano** [comment]
Perhaps "Cancel Tracing" would be more clear? I also accidentally hit Stop Tracing thinking it would stop and save the trace file :)

**Comment by randomascii** [comment]
Yep,

**Comment by randomascii** [comment]
Yep, I've heard multiple people be confused by this, and changing to Cancel Tracing is a good fix. Done. I'll push a new release at some point, and try to be less stubborn next time :-)

**Comment by randomascii** [comment]
I updated the existing release, same version number.

**Comment by amaiorano** [comment]
Thanks, Bruce! And thank you for making this wonderful tool :)
