### ISSUE TITLE
Investigating sudden High Cpu on Windows Server

### ISSUE THREAD

**Issue by abcplex** [google/UIforETW#114]
We are facing some severe issue in our production app https://serverfault.com/questions/893436/sudden-high-cpu-on-windows-server-2012-r2. Someone suggested to use this tool. I am new to ETW. Can you suggest using this tool to find the root cause of making our CPU 90-100%. I just want to find the main method that is causing issue. Also, can we run the tool on Windows Server(production)? If you have any blog to find CPU issue then it will be great.

**Comment by randomascii** [comment]
ETW is a great choice for this and UIforETW is (IMHO) a great tool for using ETW tracing. I have written a series of tutorials, available here:

https://randomascii.wordpress.com/2015/09/24/etw-central/

Good luck! ETW is a complex but very powerful tool. Luckily CPU-busy investigations are often a bit easier than some of the more esoteric tasks in ETW/WPA.

**Comment by randomascii** [comment]
I added a link from the readme to etw central in change 42852ba4fb9d8628f9a5d6c7d5af8c8638e45736 so this is now resolved.
