### ISSUE TITLE
Error: no heap-profiled processes settings found. Go to the Settings dialog to configure them.

### ISSUE THREAD

**Issue by cfeied** [google/UIforETW#125]
"Starting tracing to in-memory circular buffers...
Error: no heap-profiled processes settings found. Go to the Settings dialog to configure them."

This error newly appears after installing Version 1.50, build date Oct 5 05:48:22.
The only thing I see different in Settings is that UIFETW used to come with chrome listed as a heap-profiled process, where this version comes with nothing in that textbox.
![image](https://user-images.githubusercontent.com/18068177/46572923-e0787e00-c95b-11e8-84ee-92c0d5fa9f14.png)
![image](https://user-images.githubusercontent.com/18068177/46572924-eb331300-c95b-11e8-8356-d57c5ce16f5d.png)

**Comment by randomascii** [comment]
I have to apologize for misunderstanding this bug report. I didn't realize that you were hitting this problem even when you weren't trying to do heap tracing. I hit the problem myself a few weeks later and I have now fixed it, with change fa1b9eaa8c83d75c0142da8b71a5c91d4a8209ca. The v1.50b release includes the fix.
