### ISSUE TITLE
Can't start xperf on Windows 10 Pro for workstations 1803.

### ISSUE THREAD

**Issue by santagada** [google/UIforETW#127]
Somehow when trying UIforETW I can't get it to start on a machine, the error is:

```
Starting tracing to disk...
xperf.exe -start "NT Kernel Logger" -on Latency+POWER+DISPATCHER+DISK_IO_INIT+FILE_IO+FILE_IO_INIT+VIRT_ALLOC+MEMINFO -stackwalk Profile+CSwitch+ReadyThread -buffersize 1024 -minbuffers 1200 -maxbuffers 1200 -f "D:\TEMP\UIForETWkernel.etl" -start UIforETWSession -on Microsoft-Windows-Win32k:0xfdffffffefffffff+Multi-MAIN+Multi-FrameRate+Multi-Input+Multi-Worker+Microsoft-Windows-Kernel-Memory:0xE0+Microsoft-Windows-Kernel-Power -buffersize 1024 -minbuffers 200 -maxbuffers 200 -f "D:\TEMP\UIForETWuser.etl"
xperf: error: UIforETWSession: Invalid flags. (0x3ec).
Error starting tracing. Try stopping tracing and then starting it again?
Process exit code was 800703ec (2147943404)
```

**Comment by randomascii** [comment]
Can you try going to Settings and checking "Use other kernel logger" to see if that helps? If it does help then I can add that to the suggestions in the error message (or automatically try the other kernel logger on failures).

**Comment by santagada** [comment]
Apparently I don't have the Multi-* providers UIforETW asks for. any way to install them?

**Comment by santagada** [comment]
changing to the other kernel logger didn't make a difference.

**Comment by randomascii** [comment]
> Apparently I don't have the Multi-* providers UIforETW asks for. any way to install them?

Where did you get UIforETW from? There should be an etwpackage\bin directory which contains UIforETW.exe and also ETWProviders.dll. That is what it is looking for. These files all come from etwpackage1.50.zip.

**Comment by santagada** [comment]
actually you were right, I couldn't reproduct with 1.50

**Comment by juliusjunghans** [comment]
got the same problem with 1.56 - i am aware that 1.56 in general works. but somehow a fresh extracted etwpackage complains about that error in this older windows. is there some way to get more information?

tried the "other" solution in this post, did not work either.
