### ISSUE TITLE
Could UIForETW help in a case of getting only the necessary CPU/Process data?

### ISSUE THREAD

**Issue by altimumdelta** [google/UIforETW#142]
Hello

I have a general question, just so I don't waste time digging deeper only to figure out it's not what I expected, but I'm doing my homework of trying to listen and do as much of reading and watching of various WPT talks and explanations. 

Now the WPA stuff I'm normally doing is general game troubleshooting and beta testing to provide feedback, but there's another project which is my own with this stuff that's unrelated but coincides to be in exactly the same performance area. Once I develop my parsing utility I could analyze that with WPA to see the performance heh, so there's a more proper use case where I actually own the source and have access to symbols.

I'm doing CPU Usage stuff and the sentence that "_CPU Precise can't see what threads are doing between switching_" and that "_CPU Sampled can't see the stuff CPU Precise can_" kinda complicates things to figure what do I need to do to get everything, a complete look. However that "everything" may not be needed for what my project is about, a parsing utility for some of the select CPU and Process data, using the WPR or UIForETW sources.

This is in draft stage and what I know right now is, in terms of WPA Columns, I know it's all different under the hood, CPUs, Process, Thread ID, Starting Thread Module (not necessary), and how much a thread took on which processor.

But because I'm not a real programmer I'm not sure at all what the waits, and readying and all that stuff is all about, whether it's important or not, thread waiting for something or being ready or being idle, I didn't get that far yet, but I don't think I would need that information, I would only need when the thread is working something actively taking a CPU, and ofcourse it has to be all CPU core specific.

By default WPR even with just the "CPU Usage" resource category, seems to capture huge amounts of data in Verbose mode that that becomes even bigger when exported to CSV, which I believe I need to be able to give it to my custom written parsing utility, I might even have to write a converter to first take that CSV in and adapt it if the CSV isn't fast enough.

Perhaps there is something that could help me get up to speed out there, I even saw some parsing stuff in the UIForETW folder, but I have no Python experience and kinda want to stick with C# which I know best, I'd even do this in C++ if I had the experience but I guess that's fine. 

I've seen that these loggers are system wide and capture all processes, but I've heard wpaexporter could come in handy by extracting only thing things I need, but I'm just right now investigating that deeper if that's really the case.

The question is would UIForETW help and use it instead of WPR and then give that to wpaexporter. 

Thanks for suggestions.

**Comment by randomascii** [comment]
ETW by its nature records information across processes and UIforETW will not be doing anything to fix that.

> The question is would UIForETW help and use it instead of WPR

No. The details vary but for your purposes the information recorded is essentially identical.

A few thoughts for your project:

CPU Usage (Sampled) is good for figuring out what the CPU is doing
CPU Usage (Precise) is good for figuring out why the CPU is blocked from doing what you want it to do

Which is most appropriate depends on what your performance problem is and getting a generic parsing utility to analyze that can be tricky or even impossible.

Doing bulk trace analysis using .csv files is the wrong path to go down. There are better ways available now. See this post for details:
https://randomascii.wordpress.com/2020/01/05/bulk-etw-trace-analysis-in-c/

For all other ETW questions I recommend this page:
https://randomascii.wordpress.com/2015/09/24/etw-central/

> But because I'm not a real programmer...

Good luck. ETW analysis is tricky and, especially if you want to avoid confidently coming to wrong conclusions, often requires deep knowledge of what the operating system is doing.

**Comment by altimumdelta** [comment]
Oh, thanks for a speedy reply, yeah I wasn't sure where to ask, I'll go there for more if I need in the future.

Re reading the xperf cpu sheduling article, ... seems like the "this presentation" link is broken.

Yeah I had second thoughts about CSV ...

I do actually plan to join a real programming course so I'll probably be fine :)

**Comment by randomascii** [comment]
I deleted the bad link. Thanks for pointing that out.
