### ISSUE TITLE
No data and empty presets in new WPA even after 'Copy Startup Profiles'

### ISSUE THREAD

**Issue by WheretIB** [google/UIforETW#144]
WPA seems to be updated to version 10.0.19546.1000 (Win Build 160101.0800) and no longer displays any data for traces from UIforETW.

**Comment by WheretIB** [comment]
Downloaded the trace to another PC with WPA 10.0.18362.1, works great there.

**Comment by randomascii** [comment]
10.0.19546.1000 appears to be a preview of Windows 10 21H1, so next-year's version. I don't run any of the preview versions and it is likely that this bug will be fixed before then - and presumably it is a WPA bug. Closing.
