### ISSUE TITLE
-stackwalk: Unknown flag 'HandleCreate'

### ISSUE THREAD

**Issue by libing0526** [google/UIforETW#150]
-stackwalk: Unknown flag 'HandleCreate'
it seems like handle trace is not supported，https://docs.microsoft.com/en-us/windows-hardware/test/wpt/stackwalk

**Comment by AloisKraus** [comment]
This indicates he was using an old WPT version where xperf did no have the HandleCreate flag.

**Comment by randomascii** [comment]
I think your diagnosis is correct. I'm going to close this.
