### ISSUE TITLE
UI for ETW version 1.56 - Locks up when I choose to Start Tracing.

### ISSUE THREAD

**Issue by lviolette** [google/UIforETW#154]
UI for ETW changes to (Not Responding) right after I click on start tracing.
In the UI, it shows:
Starting tracing to disk...
Tracing is started.

Then goes to (Not Responding) in the titlebar and the whole app turns grey (like when any app shows Not Responding).
![UIforETW](https://user-images.githubusercontent.com/20373623/158677329-6258d903-355d-43cc-a4c3-f948dbce646d.PNG)

Unfortunately I can't attach the dmp file I generated with UIforETW.  Here's a public one-drive link:
https://1drv.ms/u/s!AmoCoOcZk4GBgqQOKKrSg_PiU4V9tA?e=D6pENR

**Comment by randomascii** [comment]
It is known and expected that UIforETW will hang for "a bit" when starting tracing. It invokes xperf.exe several times and doesn't pump messages again until all of those invocations have completed.

It is unusual for UIforETW to hang permanently.

So, if UIforETW hangs briefly then that is "fine". If it never recovers then that means that xperf.exe has hung. I rarely see this but it can happen. Specifically, if I have certain applications (I'm not sure which) halted in a debugger when I try to start tracing then xperf.exe will hang. I guess xperf is trying to communicate with the halted process to tell it to start emitting events.

So, look (in Task Manager) for invocations of xperf.exe that are not responding. Checking UIforETW's Show commands option may help with understanding this.

**Comment by lviolette** [comment]
Thank you for the feedback  I hadn't been able to reproduce the permanent freeze again.  Thanks for your hard work.
