### ISSUE TITLE
Record CPU Core Frequency

### ISSUE THREAD

**Issue by AloisKraus** [google/UIforETW#160]
Is it possible to record the Core Frequency along with CPU sampling or is there a hardware counter which one could employ? Power saving settings can make a big difference, but I am not sure how I can measure the impact of these.

**Comment by randomascii** [comment]
UIforETW samples the CPU speed every second or two. You can see the results in Generic Events-> UIforETW.exe-> Multi-Main-> Throttling Status. I use that to detect thermal throttling.

There is also an official CPU frequency provider. You can find it in Other-> CPU Frequency. The right-most column shows the weighted average of the CPU speed.
