### ISSUE TITLE
App is currently showing a spurious update notification

### ISSUE THREAD

**Issue by scanyard** [google/UIforETW#166]
UIForETW v1.58 is showing a message that v1.59 is up, but no such release is on GH:

![VersionNotif](https://github.com/google/UIforETW/assets/122397995/9c44f99a-58d5-4c04-b791-3b4859abf826)

**Comment by randomascii** [comment]
Whoops!

Thank you for pointing this out. I had created the release but not actually published it, so it was visible to me but not to others. I have pushed the button and it is now visible.
