### ISSUE TITLE
No "releases" of UIforETW

### ISSUE THREAD

**Issue by ariccio** [google/UIforETW#19]
[GitHub's releases feature](https://help.github.com/articles/creating-releases/) is actually really nice.

It's very convenient for less technologically-minded users, or use on non-developer machines, and it's nicely documented:

- [*"Creating Releases"*](https://help.github.com/articles/creating-releases/)
- [*"Release Your Software"*](https://github.com/blog/1547-release-your-software)
- [*"About Releases"*](https://help.github.com/articles/about-releases/)

I'm not sure how exactly it'd work with UIforETW (zip the whole `bin` folder?), but if it's not trivial, then it can be a long term goal. I've had [positive experiences](https://github.com/ariccio/altWinDirStat/releases) with it.

**Comment by randomascii** [comment]
I'll give it a try. Thanks for pointing it out.
