### ISSUE TITLE
Add power monitoring

### ISSUE THREAD

**Issue by randomascii** [google/UIforETW#36]
Perhaps using Intel Platform Power Estimation Tool (IPPET):
https://software.intel.com/en-us/forums/topic/518161

**Comment by ariccio** [comment]
Closed (?) via:

556a82e44c0525201a081efbdee21b4a3dfddd63
4ffe6af3cb74e19aff3df2f54e622485615e43c9

**Comment by randomascii** [comment]
Yep, closing.
