### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rpavlik** [google/UIforETW#43]
There appear to be a variety of licenses in this code. An Apache 2.0 license is provided, and some files (like the ETWEventDemo files) include a Google-tagged Apache 2.0 header boilerplate. In looking through, I also noticed some MIT-licensed files, but that is not a problem for me.

However, I'm looking at using a custom ETW provider, and I see that there is the seemingly-intended-to-be-reused `etwprof.h`, which bears this header comment: `Copyright (c) Cygnus Software, All rights reserved.` Since it's in the specific file, I'd imagine it overrides the implication that the rest of the code is Apache 2.0, and that therefore I only have the rights granted by copyright law and the GitHub terms.

Could this be clarified and either a) called out, if intentional, or b) remedied by inclusion of appropriate and uniform license boilerplate in each file? I'd really like to use this for more than just the super-useful GUI, but I want to make sure I'm respecting the terms under which it is offered.

**Comment by randomascii** [comment]
The intention is for all of the code to be under the Apache 2.0 license. I can correct the license information in etwprof.h. Thanks for pointing out the error.

**Comment by randomascii** [comment]
Resolved by 81b0799.
