### ISSUE TITLE
UIforETW installs 64-bit version of WPT on Windows 32-bit

### ISSUE THREAD

**Issue by ekse** [google/UIforETW#57]
WPT x64 is installed even if the 32-bit version is already installed. My setup is Windows 7 32-bit.

**Comment by randomascii** [comment]
Good point. The UIforETW support is untested on 32-bit and there are probably a few glitches like that.

I can get UIforETW to not install WPT x64. You'll then be responsible for installing the appropriate 32-bit toolkits (for Windows 7 I recommend WPT 8.1 *and* WPT 10).

I'd be interested in feedback on any other issues you observe. While I expect that 32-bit usage of UIforETW will be extremely low it might as well work.

**Comment by randomascii** [comment]
Fixed by change 5049243081. Let me know if you see any problems. You'll probably need to uninstall (or delete) the 64-bit versions of WPT.

**Comment by ekse** [comment]
Thanks!
