### ISSUE TITLE
Line endings? (core.autocrlf)

### ISSUE THREAD

**Issue by ariccio** [google/UIforETW#6]
I was going to submit a pull request, but on committing, I saw the [dreaded wall of pink](http://www.hanselman.com/blog/YoureJustAnotherCarriageReturnLineFeedInTheWall.aspx). 

The original ETWPackSymbols.py had `LF` line endings, and because GitHub defaults to core.autocrlf=true, git wants to convert the `LF` endings to `CRLF`.

What kind of line endings do you want? I can't find any guidance in either the [Chromium Python Style Guidelines](https://www.chromium.org/chromium-os/python-style-guidelines) or the [Google Python Style Guide](https://google-styleguide.googlecode.com/svn/trunk/pyguide.html).

**Comment by randomascii** [comment]
Good question. Probably CRLF is best.to match Windows norms and the C++
source. Chromium is LF endings but that's not really applicable to a
Windows only tool.

On Tue, Apr 14, 2015 at 1:29 PM, Alexander Riccio <notifications@github.com>
wrote:

> I was going to submit a pull request, but on committing, I saw the dreaded
> wall of pink
> <http://www.hanselman.com/blog/YoureJustAnotherCarriageReturnLineFeedInTheWall.aspx>.
>
>
> The original ETWPackSymbols.py had LF line endings, and because GitHub
> defaults to core.autocrlf=true, git wants to convert the LF endings to
> CRLF.
>
> What kind of line endings do you want? I can't find any guidance in either
> the Chromium Python Style Guidelines
> <https://www.chromium.org/chromium-os/python-style-guidelines> or the Google
> Python Style Guide
> <https://google-styleguide.googlecode.com/svn/trunk/pyguide.html>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/issues/6>.
>



-- 
Bruce Dawson
