### ISSUE TITLE
Max length of MSR name?

### ISSUE THREAD

**Issue by ariccio** [google/UIforETW#61]
I think we're pretty safe passing a 1024-character buffer to `GetMsrName`, but what's the actual maximum length for an MSR name? 

I couldn't find it in the Intel developers manual - although I very well could have missed it. [That manual is huge.](http://www.righto.com/2013/09/intel-x86-documentation-has-more-pages.html)

It wouldn't bother me if `GetMsrName` accepted the destination buffer's size, but right now I see no *guarantee* that `GetMsrName` won't overrun the buffer. This applies to every other application that uses the power gadget library, so it's important.

**Comment by randomascii** [comment]
The most the Intel developers manual could tell you would be the current maximum length, and we really want to know the future maximum length.

Intel's sample code uses MAX_PATH, which makes no sense, but is shorter than 1024. I think we're fine. I'll add a link to the sample code and reference.

double data[3];
int nData;
wchar_t szName[MAX_PATH];

energyLib.GetPowerData(currentNode, j, data, &nData);
energyLib.GetMsrName(j, szName);

**Comment by ariccio** [comment]
> The most the Intel developers manual could tell you would be the current maximum length, and we really want to know the future maximum length.

I wouldn't be surprised if they could actually specify a maximum length for MSR names, given that Intel assigns names themselves, and MSR names shouldn't be crazy long. 

But whatever. We're ok as it is 😊
