### ISSUE TITLE
Allow Win10 Build 10586 WPT on Win7 again

### ISSUE THREAD

**Issue by MagicAndre1981** [google/UIforETW#68]
The Th2 version Build10586 of the [Win10 WPT](https://go.microsoft.com/fwlink/p/?LinkID=698771) now  works fine with Windows 7 and includes the required events. 

In CUIforETWDlg::OnInitDialog you don't need to exclude Win7 users any longer from the Win10 Th2 version.

**Comment by randomascii** [comment]
Thanks for the update. I'll look into distributing the TH2 version and dropping the 8.1 version of WPT from the redist.

**Comment by MagicAndre1981** [comment]
ok. I've updated the link. Microsoft made a small recompile to the 10586 SDK as 10586.15

**Comment by randomascii** [comment]
Does this SDK come with the normal preview-SDK warning that it shouldn't be installed on production machines? If so then that's a bit of a problem...

**Comment by MagicAndre1981** [comment]
no, this is the official release version for Win10 Version 1511 - Fall Update 10586

**Comment by randomascii** [comment]
Okay, done, with 24e15292c8d and some preceding changes. WPT 10.0.10586.15 is now required, and is automatically installed as needed. The 8.1 WPT will be detected if present but is no longer installed, or used for much of anything. Give it a try at https://github.com/google/UIforETW/releases/tag/v1.26
