### ISSUE TITLE
uiforetw32.exe - detected as malicious by various antivirus engines

### ISSUE THREAD

**Issue by glenritchie** [google/UIforETW#71]
Release v1.28 - https://github.com/google/UIforETW/releases/download/v1.28/etwpackage.zip

uiforetw32.exe is detected by (at the time of this post) 9 anti-virus engines as malicious.

See: https://www.virustotal.com/en/file/ef59759757396d329b9a2fd25fef83c58ffe49a6004baa4b49bcc8ab0dffbd71/analysis/

**Comment by randomascii** [comment]
Well that's unfortunate. Any idea why? My guess is that it's just a false positive, but if the binary is corrupted that would be pretty bad.

At least it's only the 32-bit version, which virtually nobody should be using anyway.

**Comment by ariccio** [comment]
It's [up to twelve now](https://www.virustotal.com/en/file/c1186a7d36e81db6b98f2b5430d945e31bc7f59d45656f72a8e300b7db049487/analysis/1455003471/)... huh? The 64 bit executable [has two detections](https://www.virustotal.com/en/file/b43585b381a0fe7f974372eaeb50e57e4a42c3926b73b9c9001d3a550d6ddd6b/analysis/).

@randomascii just for safety, maybe you should run a full system antimalware scan? I'll do so later tonight. I don't expect to find anything, but at least it's a good excuse for a full system scan.

**Comment by glenritchie** [comment]
I've submitted it to Bitdefender for review, my version quarantined it when I downloaded it, I'll let you know what they reply with if I get a response.

**Comment by glenritchie** [comment]
No longer detected by Bitdefender but still showing malicious by 5 anti-virus engines ( McAfee being the most well known).

Perhaps add a notice to the releases page letting people know it could be a false positive?

**Comment by randomascii** [comment]
I added a note to the latest release, linking to this issue.

**Comment by snowkoan** [comment]
You might try signing your release binaries. These days, no signature is a warning sign for anti-malware engines.

**Comment by randomascii** [comment]
Binaries are signed now. Virustotal now gives UIforETW.exe a clean bill of health - 0/60. UIforETW32.exe gets a score of 0/60 also. Closing as fixed?
