### ISSUE TITLE
%etwtracedir% in etw_cpuusage_longterm.bat should be quoted

### ISSUE THREAD

**Issue by ariccio** [google/UIforETW#72]
These three lines:
```
@rem Make sure %etwtracedir% exists
@if exist %etwtracedir% goto TraceDirExists
@mkdir %etwtracedir%
```
should really be:
```
@rem Make sure %etwtracedir% exists
@if exist "%etwtracedir%" goto TraceDirExists
@mkdir "%etwtracedir%"
```

I'd submit a PR, but my local install of Git is acting up. Grr.

**Comment by randomascii** [comment]
Wow - lots of missing quotes. Dozens of them, in etwrecord.bat. I'm fixing and testing them all. Thanks for the report.

**Comment by randomascii** [comment]
Fixed, along with a host of related bugs, with commit cf5e5c954059d.
