### ISSUE TITLE
internal error on second build

### ISSUE THREAD

**Issue by MikeMarcin** [google/UIforETW#75]
Using VS2015 Update 2 RC compiling for Win32 or x64 with a release configuration I get an internal error the second time I build.

I can work around this by deleting bin\UIforETW_devrel.iobj between builds.

This issue does not occur with a debug configuration.

I suspect it's a compiler bug but I don't know the project well enough to submit it as such to Microsoft.

1>------ Build started: Project: UIforETW, Configuration: Release x64 ------
1>  UIforETWDlg.cpp
1>  Generating code
1>c:\code\uiforetw\uiforetw\workingset.cpp : fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 249)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>    link!RaiseException()+0x48
1>    link!RaiseException()+0x48
1>    link!CxxThrowException()+0x65
1>    link!std::_Xout_of_range()+0x1f
1>    link!InvokeCompilerPass()+0x252c9
1>    link!InvokeCompilerPass()+0x1b56e
1>    link!InvokeCompilerPass()+0x22eec
1>    link!InvokeCompilerPass()+0x2332e
1>    link!InvokeCompilerPass()+0x232f9
1>    link!InvokeCompilerPass()+0x233cb
1>    link!InvokeCompilerPass()+0x22b04
1>    link!InvokeCompilerPass()+0x22d86
1>    link!DllGetC2Telemetry()+0x115837
1>
1>c:\code\uiforetw\uiforetw\workingset.cpp : fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 249)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>    link!RaiseException()+0x48
1>    link!CxxThrowException()+0x65
1>    link!std::_Xout_of_range()+0x1f
1>    link!InvokeCompilerPass()+0x252c9
1>    link!InvokeCompilerPass()+0x1b56e
1>    link!InvokeCompilerPass()+0x22eec
1>    link!InvokeCompilerPass()+0x2332e
1>    link!InvokeCompilerPass()+0x232f9
1>    link!InvokeCompilerPass()+0x233cb
1>    link!InvokeCompilerPass()+0x22b04
1>    link!InvokeCompilerPass()+0x22d86
1>    link!DllGetC2Telemetry()+0x115837
1>
1>LINK : fatal error LNK1257: code generation failed
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by randomascii** [comment]
Internal compiler errors are *always* compiler bugs, so that part of the diagnosis is easy. Can you repro the bug reliably? If so then I would wait for Update 2 final to ship (probably very soon) and see if it still happens. If so then either file a bug (https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm) or I will.

**Comment by MikeMarcin** [comment]
CNR in final Update 2.
looks like they fixed it
