### ISSUE TITLE
Allow Win10 SDK on Win7 machines

### ISSUE THREAD

**Issue by briterator** [google/UIforETW#99]
Hi Bruce,
The limitation that prevents UIforETW from working when a windows 7 machine has the windows 10 sdk installed makes this tool unusable for video game developers. There is a certain video game console which requires you to install the windows 10 SDK even on a windows 7 machine. If I were to uninstall it I would be unable to actually do my job.

The error I'm referring to states:
"The installed version of Windows Performance Toolkit is not compatible with windows 7. Please uninstall it and run UIforETW again."

I imagine it should be feasible to fallback to an earlier version of windows performance toolkit if the newest one is incompatible. I have multiple versions installed.

**Comment by randomascii** [comment]
UIforETW is merely reporting the reality which is that that version of WPT will not work on Windows 7. You could remove the check from UIforETW (it is open source) but then you would get a failure when trying to record traces or analyze traces, which is not really progress.

The bad version of WPT shipped with Windows 10 Anniversary Edition. The ideal version to use is the one prior to that. UIforETW ships with an installer for that previous version , in etwpackage\third_party\oldwpt10. However that won't install if the more recent version is installed.

So, your best solution is to run that installer on another machine and then copy the results over to the "c:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit" directory. That will give you the most recent version that works on Windows 7.

Falling back to an even earlier version would be a huge step backwards that I have no interest in supporting.

And, you should complain to Microsoft about this ridiculous situation. Among other mistakes they should not be *allowing* a version of WPT that will not run on Windows 7 to install there.
